name: Generate Contribution Snake

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: "0 3 * * *" # daily at 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # allows committing generated SVG

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: ./output/github-contribution-grid-snake.svg

      - name: Commit generated SVG (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg || true
          if ! git diff --staged --quiet; then
            git commit -m "chore: update contribution snake (auto)" || echo "No commit created"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
